#[derive(Default)]
pub struct Cp0 {
    pub index: u32,
    pub random: u32,
    pub entry_lo0: u64,
    pub entry_lo1: u64,
    pub context: u64,
    pub page_mask: u32,
    pub wired: u32,
    pub bad_vaddr: u64,
    pub count: u32,
    pub entry_hi: u64,
    pub compare: u32,
    pub status: u32,
    pub cause: u32,
    pub epc: u64,
    pub prid: u32,
    pub config: u32,
    pub lladdr: u32,
    pub watch_lo: u32,
    pub watch_hi: u32,
    pub xcontext: u32,
    pub parity_error: u32,
    pub cache_error: u32,
    pub tag_lo: u32,
    pub tag_hi: u32,
    pub error_epc: u64,
}